"""Update schedule model

Revision ID: 00ce0aa6389a
Revises: 49011ed54e56
Create Date: 2024-03-16 19:24:26.636848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ce0aa6389a'
down_revision = '49011ed54e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appt_time', sa.Integer(), nullable=False))
        batch_op.drop_column('appt_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appt_hour', sa.INTEGER(), nullable=False))
        batch_op.drop_column('appt_time')

    # ### end Alembic commands ###
