"""Add schedule table

Revision ID: 1f5f75a3564d
Revises: 9f85b723678b
Create Date: 2024-01-01 18:54:21.408660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5f75a3564d'
down_revision = '9f85b723678b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('appt_date', sa.Date(), nullable=False),
    sa.Column('appt_hour', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('appt_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
