"""Update Schedule model

Revision ID: 31bc0eaeb5ac
Revises: a4a5b5c019de
Create Date: 2024-01-02 21:46:50.851983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bc0eaeb5ac'
down_revision = 'a4a5b5c019de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_2', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('status_2')

    # ### end Alembic commands ###
