"""Update appointment model

Revision ID: 3c5f8574fd48
Revises: 3d639af8be15
Create Date: 2023-08-06 22:02:01.856630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5f8574fd48'
down_revision = '3d639af8be15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=32), nullable=True))
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=11),
               existing_nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('contact_number',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
