"""Add model for schedule

Revision ID: 41dec8e15847
Revises: 3c5f8574fd48
Create Date: 2023-08-13 22:27:42.884944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dec8e15847'
down_revision = '3c5f8574fd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot_9', sa.Integer(), nullable=True),
    sa.Column('time_slot_10', sa.Integer(), nullable=True),
    sa.Column('time_slot_11', sa.Integer(), nullable=True),
    sa.Column('time_slot_12', sa.Integer(), nullable=True),
    sa.Column('time_slot_13', sa.Integer(), nullable=True),
    sa.Column('time_slot_14', sa.Integer(), nullable=True),
    sa.Column('time_slot_15', sa.Integer(), nullable=True),
    sa.Column('time_slot_16', sa.Integer(), nullable=True),
    sa.Column('time_slot_17', sa.Integer(), nullable=True),
    sa.Column('time_slot_18', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
