"""Create appointment and schedule models

Revision ID: 83dad1292ec3
Revises: 
Create Date: 2024-01-03 22:55:23.363077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dad1292ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('contact_number', sa.String(length=11), nullable=True),
    sa.Column('appt_date', sa.Date(), nullable=True),
    sa.Column('appt_time', sa.Time(), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appt_date', sa.Date(), nullable=True),
    sa.Column('appt_hour', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('appointment')
    # ### end Alembic commands ###
