"""Remove schedule table

Revision ID: 9f85b723678b
Revises: 41dec8e15847
Create Date: 2023-09-30 21:18:46.951385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f85b723678b'
down_revision = '41dec8e15847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time_slot_9', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_10', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_11', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_12', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_13', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_14', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_15', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_16', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_17', sa.INTEGER(), nullable=True),
    sa.Column('time_slot_18', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###
