"""Update Schedule model

Revision ID: c393b4075353
Revises: edcb710d952b
Create Date: 2024-01-02 21:53:23.332830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c393b4075353'
down_revision = 'edcb710d952b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('status_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_2', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
