"""Update Schedule model

Revision ID: d794b120486f
Revises: 31bc0eaeb5ac
Create Date: 2024-01-02 21:50:07.157923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd794b120486f'
down_revision = '31bc0eaeb5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('status_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_2', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
