"""Update appointment and schedule models

Revision ID: eff1af646f81
Revises: 83dad1292ec3
Create Date: 2024-01-04 21:19:23.397583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff1af646f81'
down_revision = '83dad1292ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('appt_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('appt_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('appt_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('appt_hour',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('appt_hour',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('appt_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('appt_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('appt_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('contact_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
